var pages = [{'name': 'sealed class QueryTextEvent', 'description':'reactivecircus.flowbinding.appcompat.QueryTextEvent', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/-query-text-event/index.html', 'searchKey':'QueryTextEvent'},
{'name': 'class QueryChanged(view: SearchView, queryText: CharSequence) : QueryTextEvent', 'description':'reactivecircus.flowbinding.appcompat.QueryTextEvent.QueryChanged', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/-query-text-event/-query-changed/index.html', 'searchKey':'QueryChanged'},
{'name': 'fun QueryChanged(view: SearchView, queryText: CharSequence)', 'description':'reactivecircus.flowbinding.appcompat.QueryTextEvent.QueryChanged.QueryChanged', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/-query-text-event/-query-changed/-query-changed.html', 'searchKey':'QueryChanged'},
{'name': 'class QuerySubmitted(view: SearchView, queryText: CharSequence) : QueryTextEvent', 'description':'reactivecircus.flowbinding.appcompat.QueryTextEvent.QuerySubmitted', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/-query-text-event/-query-submitted/index.html', 'searchKey':'QuerySubmitted'},
{'name': 'fun QuerySubmitted(view: SearchView, queryText: CharSequence)', 'description':'reactivecircus.flowbinding.appcompat.QueryTextEvent.QuerySubmitted.QuerySubmitted', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/-query-text-event/-query-submitted/-query-submitted.html', 'searchKey':'QuerySubmitted'},
{'name': 'fun PopupMenu.dismisses(): Flow<Unit>', 'description':'reactivecircus.flowbinding.appcompat.dismisses', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/dismisses.html', 'searchKey':'dismisses'},
{'name': 'fun Toolbar.navigationClicks(): Flow<Unit>', 'description':'reactivecircus.flowbinding.appcompat.navigationClicks', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/navigation-clicks.html', 'searchKey':'navigationClicks'},
{'name': 'fun SearchView.queryTextChanges(): InitialValueFlow<CharSequence>', 'description':'reactivecircus.flowbinding.appcompat.queryTextChanges', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/query-text-changes.html', 'searchKey':'queryTextChanges'},
{'name': 'fun SearchView.queryTextEvents(): InitialValueFlow<QueryTextEvent>', 'description':'reactivecircus.flowbinding.appcompat.queryTextEvents', 'location':'flowbinding-appcompat/reactivecircus.flowbinding.appcompat/query-text-events.html', 'searchKey':'queryTextEvents'}]
