var pages = [{'name': 'data class ScrollChangeEvent(view: View, scrollX: Int, scrollY: Int, oldScrollX: Int, oldScrollY: Int)', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/index.html', 'searchKey':'ScrollChangeEvent'},
{'name': 'fun ScrollChangeEvent(view: View, scrollX: Int, scrollY: Int, oldScrollX: Int, oldScrollY: Int)', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent.ScrollChangeEvent', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/-scroll-change-event.html', 'searchKey':'ScrollChangeEvent'},
{'name': 'operator fun component1(): View', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent.component1', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/component1.html', 'searchKey':'component1'},
{'name': 'operator fun component2(): Int', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent.component2', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/component2.html', 'searchKey':'component2'},
{'name': 'operator fun component3(): Int', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent.component3', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/component3.html', 'searchKey':'component3'},
{'name': 'operator fun component4(): Int', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent.component4', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/component4.html', 'searchKey':'component4'},
{'name': 'operator fun component5(): Int', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent.component5', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/component5.html', 'searchKey':'component5'},
{'name': 'fun copy(view: View, scrollX: Int, scrollY: Int, oldScrollX: Int, oldScrollY: Int): ScrollChangeEvent', 'description':'reactivecircus.flowbinding.core.ScrollChangeEvent.copy', 'location':'flowbinding-core/reactivecircus.flowbinding.core/-scroll-change-event/copy.html', 'searchKey':'copy'},
{'name': 'fun NestedScrollView.scrollChangeEvents(): Flow<ScrollChangeEvent>', 'description':'reactivecircus.flowbinding.core.scrollChangeEvents', 'location':'flowbinding-core/reactivecircus.flowbinding.core/scroll-change-events.html', 'searchKey':'scrollChangeEvents'}]
