version: 2.1

# Cache
extract_cache_version: &extract_cache_version
  run:
    name: Extract cache version from environment variable
    command: |
      echo "Cache version: $CACHE_VERSION"
      echo "$CACHE_VERSION" > cacheVersion

save_gradle_cache: &save_gradle_cache
  save_cache:
    key: gradle-{{ checksum "cacheVersion" }}-{{ checksum "buildSrc/dependencies.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
      - ~/.gradle

restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    key: gradle-{{ checksum "cacheVersion" }}-{{ checksum "buildSrc/dependencies.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

executors:
  android:
    docker:
      - image: reactivecircus/android-sdk:latest
    working_directory: ~/FlowBinding
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process'
      TERM: dumb

jobs:
  build_and_test:
    executor: android
    steps:
      - checkout
      - *extract_cache_version
      - *restore_gradle_cache
      - run:
          name: Assemble
          command: ./gradlew assemble
      - run:
          name: Run Checks (test, detekt and lint)
          command: |
            ./gradlew test detekt lintDebug
      - *save_gradle_cache

  publish_artifacts:
    executor: android
    steps:
      - checkout
      - run:
          name: Export Sonatype Credentials
          command: |
            echo "SONATYPE_NEXUS_USERNAME=${SONATYPE_NEXUS_USERNAME}" >> gradle.properties
            echo "SONATYPE_NEXUS_PASSWORD=${SONATYPE_NEXUS_PASSWORD}" >> gradle.properties
      - *extract_cache_version
      - *restore_gradle_cache
      - run:
          name: Deploy Snapshot
          command: .buildscript/deploy_snapshot.sh
      - *save_gradle_cache

workflows:
  build-test-deploy:
    jobs:
      - build_and_test
      - publish_artifacts:
          filters:
            branches:
              only: master
          requires:
            - build_and_test
