name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CI: true
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false
  TERM: dumb

jobs:
  assemble:
    name: Assemble
    runs-on: macos-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - run: |
          ./gradlew assemble

  checks:
    name: Checks (unit tests, static analysis and binary compatibility API check)
    runs-on: macos-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - run: |
          ./gradlew test apiCheck detekt lintDebug -PslimTests

  deploy-snapshot:
    name: Deploy snapshot
    needs: [assemble, checks]
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
      ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - run: |
          ./gradlew clean androidSourcesJar androidJavadocsJar uploadArchives --no-daemon --no-parallel
